<a href="https://colab.research.google.com/github/o-umarov/praktika/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
print(pd.__version__)

2.2.3

In [ ]:
mydataset = {
    'cars': ["BMW", "Volvo", "Ford", "Tesla", "Bugatti", "VolksVagen", "KIA 5"],
    'passings': [3, 5, 7, 4, 7, 5, 8]
}

dataframe = pd.DataFrame(mydataset)
print(dataframe)

         cars  passings
0         BMW         3
1       Volvo         5
2        Ford         7
3       Tesla         4
4     Bugatti         7
5  VolksVagen         5
6       KIA 5         8

In [ ]:
dataframe.head(10) # shows a top list of items

         cars  passings
0         BMW         3
1       Volvo         5
2        Ford         7
3       Tesla         4
4     Bugatti         7
5  VolksVagen         5
6       KIA 5         8

In [ ]:
dataframe.tail() # show a reverse list of items

         cars  passings
2        Ford         7
3       Tesla         4
4     Bugatti         7
5  VolksVagen         5
6       KIA 5         8

In [ ]:
dataframe.shape # used to determine the shape of tabular data

(7, 2)

In [ ]:
dataframe.columns # used to identify the number of columns

Index(['cars', 'passings'], dtype='object')

In [ ]:
dataframe.dtypes # used to identify the type of tabular data features

cars        object
passings     int64
dtype: object

In [ ]:
dataframe.describe() # used to describe the numerical columns

       passings
count  7.000000
mean   5.571429
std    1.812654
min    3.000000
25%    4.500000
50%    5.000000
75%    7.000000
max    8.000000

In [ ]:
# iloc() - used to retrieve data according to integer position
dataframe.iloc[0:5]

      cars  passings
0      BMW         3
1    Volvo         5
2     Ford         7
3    Tesla         4
4  Bugatti         7

In [ ]:
# loc(2 args) - used to retrieve data from a table according to their int position and column feature names
dataframe.loc[1:5, "cars"]

1         Volvo
2          Ford
3         Tesla
4       Bugatti
5    VolksVagen
Name: cars, dtype: object

In [ ]:
print(dataframe)

         cars  passings
0         BMW         3
1       Volvo         5
2        Ford         7
3       Tesla         4
4     Bugatti         7
5  VolksVagen         5
6       KIA 5         8

In [ ]:
dataframe[dataframe["passings"] !=4] # Conditional selection via operators

         cars  passings
0         BMW         3
1       Volvo         5
2        Ford         7
4     Bugatti         7
5  VolksVagen         5
6       KIA 5         8

In [ ]:
# dataframe.mean(numeric_only=True)  - central value
dataframe["passings"].mean()

np.float64(5.571428571428571)

In [ ]:
# sum() - used to get a sum of all numeric and char values
dataframe["passings"].sum()

np.int64(39)

In [ ]:
dataframe.min()

cars        BMW
passings      3
dtype: object

In [ ]:
dataframe.max()

cars        Volvo
passings        8
dtype: object

In [ ]:
dataframe.median(numeric_only=True)

passings    5.0
dtype: float64

In [ ]:
dataframe.count()

cars        7
passings    7
dtype: int64

In [ ]:
dataframe.std(numeric_only=True)

passings    1.812654
dtype: float64

In [ ]:
data_with_missing = {
    "cars": ["BMW", None, "Toyota", "Tesla", None, "KIA5", "Genesis"],
    "counts": [None, 3, 4, None, 5, 7, None]
}
df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     NaN
1     None     3.0
2   Toyota     4.0
3    Tesla     NaN
4     None     5.0
5     KIA5     7.0
6  Genesis     NaN

In [ ]:
df_missing.isnull().sum()

cars      2
counts    3
dtype: int64

In [ ]:
df_missing.dropna(subset=["cars"])
# df_missing.dropna(subset=["counts"])

     cars  counts
1    None     3.0
2  Toyota     4.0
4    None     5.0
5    KIA5     7.0

In [ ]:
df_missing.fillna({"cars": "Unknown", "counts": 0})

      cars  counts
0      BMW     0.0
1  Unknown     3.0
2   Toyota     4.0
3    Tesla     0.0
4  Unknown     5.0
5     KIA5     7.0
6  Genesis     0.0

In [ ]:
titanic = pd.read_csv("Titanic-Dataset.csv")
titanic.tail(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
excel = pd.read_excel("example.xlsx")
excel.tail()
# excel1 = pd.read_json("NameOfTheJSONFile")

,Country,Year,Rank,Total,S1: Demographic Pressures,S2: Refugees and IDPs,C3: Group Grievance,E3: Human Flight and Brain Drain,E2: Economic Inequality,E1: Economy,P1: State Legitimacy,P2: Public Services,P3: Human Rights,C1: Security Apparatus,C2: Factionalized Elites,X1: External Intervention
174,Switzerland,2023,175th,17.8,2.4,3.2,2.1,1.0,2.4,1.6,0.3,1.6,0.4,1.4,1.0,0.4
175,New Zealand,2023,176th,16.7,1.1,1.2,2.0,1.6,2.6,2.6,0.5,1.1,0.5,1.6,1.4,0.5
176,Finland,2023,177th,16.0,1.7,1.9,0.3,1.5,1.6,2.7,0.4,1.0,0.5,2.0,1.4,1.0
177,Iceland,2023,178th,15.7,1.5,1.5,0.5,1.6,1.5,2.6,0.4,0.9,0.4,0.4,1.8,2.6
178,Norway,2023,179th,14.5,1.4,1.7,3.1,0.7,1.4,1.4,0.4,1.0,0.4,1.4,1.1,0.5

In [ ]:
titanic.to_excel("output-test.xlsx")

In [ ]:
# Series - for 1D arrays
cars = pd.Series(["BMW", "Tesla", "Ferrari", "Toyota"])
print(f" {cars}")

 0        BMW
1      Tesla
2    Ferrari
3     Toyota
dtype: object

In [ ]:
cars_series = data_with_missing["cars"]
print(cars_series)

['BMW', None, 'Toyota', 'Tesla', None, 'KIA5', 'Genesis']